version: '3.1'

services:
  web:
    build:
       context: .
       dockerfile: ./docker/Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "8000:80"
    environment:
      REDIS_URI: redis://redis:6379/1
      DEBUG: "True"

    # 开发模式配置
    entrypoint: /app/docker/entrypoint-dev.sh
    volumes:
      - .:/app
      - ./runtest:/bin/runtest
    command: []
    tty: true

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"