version: '3.1'

services:
  web:
    build:
       context: .
       dockerfile: ./docker/Dockerfile
    depends_on:
      - redis
    ports:
      - "8000:80"
    environment:
      REDIS_URI: redis://redis:6379/1
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:

      NEW_RELIC_LICENSE_KEY:
      SENTRY_DSN:
      DEBUG: 'True'
      JWT_SECRET: 'tiny.tec'

      MM_TOKEN: ''
      MM_AES_KEY: ''
      MM_APP_ID: ''
      MM_APP_SECRET: ''

    # 开发模式配置
    entrypoint: /app/docker/entrypoint-dev.sh
    volumes:
      - .:/app
      - ./runtest:/bin/runtest
    command: []
    tty: true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"